name: documentation
on:
  workflow_call:
jobs:
  readme:
    runs-on: ubuntu-latest
    container:
      image: quay.io/terraform-docs/terraform-docs:0.17.0
    steps:
      - name: Install pre-requisites
        run: apk update && apk add git git-lfs

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TFDocs
        run: |
          terraform-docs markdown . > README.md || exit $?
          git diff --exit-code