name: Release Pipeline
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
        default: 'PATCH'
        type: choice
        options:
          - "PATCH"
          - "MINOR"
          - "MAJOR"

jobs:
  ValidateTags:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Latest Commit Tag
        run: |
          LATEST_TAG=$(git tag --points-at HEAD)
          if [[ -n "$LATEST_TAG" ]]; then
            echo "Latest Tag: $LATEST_TAG"
            echo "[ERROR] Tag already exists on branch HEAD"
            exit 1
          fi

  CreateTag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    continue-on-error: false
    needs:
      - ValidateTags
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate New Tag
        id: version_tag
        uses: ./.github/actions/semver
        with:
          release: ${{ github.event.inputs.release }}

      - name: Set Version Tag
        id: new_tag_version
        run: |
          NEW_TAG=${{ steps.version_tag.outputs.version_tag }}
          echo "New Tag - $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Push Latest Tag
        id: create_tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.new_tag_version.outputs.new_tag}}',
              sha: context.sha
            })